# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.28

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/moltony/dev/pikurosu

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/moltony/dev/pikurosu

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/moltony/dev/pikurosu/CMakeFiles /home/moltony/dev/pikurosu//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/moltony/dev/pikurosu/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named Pikurosu

# Build rule for target.
Pikurosu: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Pikurosu
.PHONY : Pikurosu

# fast build rule for target.
Pikurosu/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Pikurosu.dir/build.make CMakeFiles/Pikurosu.dir/build
.PHONY : Pikurosu/fast

lib/SDL_FontCache/SDL_FontCache.o: lib/SDL_FontCache/SDL_FontCache.c.o
.PHONY : lib/SDL_FontCache/SDL_FontCache.o

# target to build an object file
lib/SDL_FontCache/SDL_FontCache.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Pikurosu.dir/build.make CMakeFiles/Pikurosu.dir/lib/SDL_FontCache/SDL_FontCache.c.o
.PHONY : lib/SDL_FontCache/SDL_FontCache.c.o

lib/SDL_FontCache/SDL_FontCache.i: lib/SDL_FontCache/SDL_FontCache.c.i
.PHONY : lib/SDL_FontCache/SDL_FontCache.i

# target to preprocess a source file
lib/SDL_FontCache/SDL_FontCache.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Pikurosu.dir/build.make CMakeFiles/Pikurosu.dir/lib/SDL_FontCache/SDL_FontCache.c.i
.PHONY : lib/SDL_FontCache/SDL_FontCache.c.i

lib/SDL_FontCache/SDL_FontCache.s: lib/SDL_FontCache/SDL_FontCache.c.s
.PHONY : lib/SDL_FontCache/SDL_FontCache.s

# target to generate assembly for a file
lib/SDL_FontCache/SDL_FontCache.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Pikurosu.dir/build.make CMakeFiles/Pikurosu.dir/lib/SDL_FontCache/SDL_FontCache.c.s
.PHONY : lib/SDL_FontCache/SDL_FontCache.c.s

lib/libmtnlog/source/mtnlog.o: lib/libmtnlog/source/mtnlog.c.o
.PHONY : lib/libmtnlog/source/mtnlog.o

# target to build an object file
lib/libmtnlog/source/mtnlog.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Pikurosu.dir/build.make CMakeFiles/Pikurosu.dir/lib/libmtnlog/source/mtnlog.c.o
.PHONY : lib/libmtnlog/source/mtnlog.c.o

lib/libmtnlog/source/mtnlog.i: lib/libmtnlog/source/mtnlog.c.i
.PHONY : lib/libmtnlog/source/mtnlog.i

# target to preprocess a source file
lib/libmtnlog/source/mtnlog.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Pikurosu.dir/build.make CMakeFiles/Pikurosu.dir/lib/libmtnlog/source/mtnlog.c.i
.PHONY : lib/libmtnlog/source/mtnlog.c.i

lib/libmtnlog/source/mtnlog.s: lib/libmtnlog/source/mtnlog.c.s
.PHONY : lib/libmtnlog/source/mtnlog.s

# target to generate assembly for a file
lib/libmtnlog/source/mtnlog.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Pikurosu.dir/build.make CMakeFiles/Pikurosu.dir/lib/libmtnlog/source/mtnlog.c.s
.PHONY : lib/libmtnlog/source/mtnlog.c.s

src/board.o: src/board.c.o
.PHONY : src/board.o

# target to build an object file
src/board.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Pikurosu.dir/build.make CMakeFiles/Pikurosu.dir/src/board.c.o
.PHONY : src/board.c.o

src/board.i: src/board.c.i
.PHONY : src/board.i

# target to preprocess a source file
src/board.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Pikurosu.dir/build.make CMakeFiles/Pikurosu.dir/src/board.c.i
.PHONY : src/board.c.i

src/board.s: src/board.c.s
.PHONY : src/board.s

# target to generate assembly for a file
src/board.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Pikurosu.dir/build.make CMakeFiles/Pikurosu.dir/src/board.c.s
.PHONY : src/board.c.s

src/game.o: src/game.c.o
.PHONY : src/game.o

# target to build an object file
src/game.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Pikurosu.dir/build.make CMakeFiles/Pikurosu.dir/src/game.c.o
.PHONY : src/game.c.o

src/game.i: src/game.c.i
.PHONY : src/game.i

# target to preprocess a source file
src/game.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Pikurosu.dir/build.make CMakeFiles/Pikurosu.dir/src/game.c.i
.PHONY : src/game.c.i

src/game.s: src/game.c.s
.PHONY : src/game.s

# target to generate assembly for a file
src/game.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Pikurosu.dir/build.make CMakeFiles/Pikurosu.dir/src/game.c.s
.PHONY : src/game.c.s

src/main.o: src/main.c.o
.PHONY : src/main.o

# target to build an object file
src/main.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Pikurosu.dir/build.make CMakeFiles/Pikurosu.dir/src/main.c.o
.PHONY : src/main.c.o

src/main.i: src/main.c.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Pikurosu.dir/build.make CMakeFiles/Pikurosu.dir/src/main.c.i
.PHONY : src/main.c.i

src/main.s: src/main.c.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Pikurosu.dir/build.make CMakeFiles/Pikurosu.dir/src/main.c.s
.PHONY : src/main.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... Pikurosu"
	@echo "... lib/SDL_FontCache/SDL_FontCache.o"
	@echo "... lib/SDL_FontCache/SDL_FontCache.i"
	@echo "... lib/SDL_FontCache/SDL_FontCache.s"
	@echo "... lib/libmtnlog/source/mtnlog.o"
	@echo "... lib/libmtnlog/source/mtnlog.i"
	@echo "... lib/libmtnlog/source/mtnlog.s"
	@echo "... src/board.o"
	@echo "... src/board.i"
	@echo "... src/board.s"
	@echo "... src/game.o"
	@echo "... src/game.i"
	@echo "... src/game.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

